# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TestPlugin_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TestPluginDialogBase(object):
    def setupUi(self, TestPluginDialogBase):
        TestPluginDialogBase.setObjectName("TestPluginDialogBase")
        TestPluginDialogBase.resize(510, 376)
        self.button_box = QtWidgets.QDialogButtonBox(TestPluginDialogBase)
        self.button_box.setGeometry(QtCore.QRect(80, 330, 405, 28))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.gridLayoutWidget = QtWidgets.QWidget(TestPluginDialogBase)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(66, 170, 391, 135))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_mousetool = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_mousetool.setObjectName("btn_mousetool")
        self.gridLayout.addWidget(self.btn_mousetool, 0, 1, 1, 1)
        self.btn_clicktool = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_clicktool.setObjectName("btn_clicktool")
        self.gridLayout.addWidget(self.btn_clicktool, 0, 0, 1, 1)
        self.btn_clear = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_clear.setObjectName("btn_clear")
        self.gridLayout.addWidget(self.btn_clear, 0, 2, 1, 1)
        self.btn_start = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_start.setObjectName("btn_start")
        self.gridLayout.addWidget(self.btn_start, 5, 0, 1, 3)
        self.btn_save = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_save.sizePolicy().hasHeightForWidth())
        self.btn_save.setSizePolicy(sizePolicy)
        self.btn_save.setObjectName("btn_save")
        self.gridLayout.addWidget(self.btn_save, 6, 0, 1, 3)
        self.layoutWidget = QtWidgets.QWidget(TestPluginDialogBase)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 20, 413, 141))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.progressBar = QtWidgets.QProgressBar(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_2.addWidget(self.progressBar, 1, 1, 1, 1)
        self.label_1 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_1.sizePolicy().hasHeightForWidth())
        self.label_1.setSizePolicy(sizePolicy)
        self.label_1.setObjectName("label_1")
        self.gridLayout_2.addWidget(self.label_1, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_coor = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_coor.sizePolicy().hasHeightForWidth())
        self.label_coor.setSizePolicy(sizePolicy)
        self.label_coor.setObjectName("label_coor")
        self.gridLayout_2.addWidget(self.label_coor, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_0 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_0.sizePolicy().hasHeightForWidth())
        self.label_0.setSizePolicy(sizePolicy)
        self.label_0.setAlignment(QtCore.Qt.AlignCenter)
        self.label_0.setObjectName("label_0")
        self.gridLayout_2.addWidget(self.label_0, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.mMapLayerComboBox = QgsMapLayerComboBox(self.layoutWidget)
        self.mMapLayerComboBox.setObjectName("mMapLayerComboBox")
        self.gridLayout_2.addWidget(self.mMapLayerComboBox, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 3, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.mMapLayerComboBox_2 = QgsMapLayerComboBox(self.layoutWidget)
        self.mMapLayerComboBox_2.setObjectName("mMapLayerComboBox_2")
        self.gridLayout_2.addWidget(self.mMapLayerComboBox_2, 3, 1, 1, 1)

        self.retranslateUi(TestPluginDialogBase)
        self.button_box.accepted.connect(TestPluginDialogBase.accept)
        self.button_box.rejected.connect(TestPluginDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(TestPluginDialogBase)

    def retranslateUi(self, TestPluginDialogBase):
        _translate = QtCore.QCoreApplication.translate
        TestPluginDialogBase.setWindowTitle(_translate("TestPluginDialogBase", "TestPlugin"))
        self.btn_mousetool.setText(_translate("TestPluginDialogBase", "打開/關閉修改工具"))
        self.btn_clicktool.setText(_translate("TestPluginDialogBase", "打開/關閉選取工具"))
        self.btn_clear.setText(_translate("TestPluginDialogBase", "清除已選圖徵"))
        self.btn_start.setText(_translate("TestPluginDialogBase", "開始計算"))
        self.btn_save.setText(_translate("TestPluginDialogBase", "儲存結果並輸出"))
        self.label_1.setText(_translate("TestPluginDialogBase", "計算進度："))
        self.label_coor.setText(_translate("TestPluginDialogBase", "請使用選取工具點擊河道圖層任一圖徵..."))
        self.label_0.setText(_translate("TestPluginDialogBase", "起始座標：\n"
"(只顯示小數點後1位)"))
        self.label_2.setText(_translate("TestPluginDialogBase", "河道圖層："))
        self.label_3.setText(_translate("TestPluginDialogBase", "集水區圖層："))
from qgsmaplayercombobox import QgsMapLayerComboBox
